"""p2_m001_m005_domain_schema

Revision ID: 5a4e8291af21
Revises:
Create Date: 2026-10-04 00:24:09.307701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a4e8291af21"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("edition", sa.String(length=100), nullable=True),
        sa.Column("locator", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_sources")),
    )
    op.create_table(
        "systems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_systems")),
    )
    op.create_table(
        "taxonomies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("version_label", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomies")),
    )
    op.create_table(
        "system_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("parent_version_id", sa.Uuid(), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["system_versions.id"],
            name=op.f("fk_system_versions_parent_version_id_system_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
            name=op.f("fk_system_versions_system_id_systems"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_versions")),
    )
    with op.batch_alter_table("system_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_system_versions_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_system_versions_system_id"),
            ["system_id"],
            unique=False,
        )

    op.create_table(
        "taxonomy_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("taxonomy_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_taxonomy_nodes_parent_id_taxonomy_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_id"],
            ["taxonomies.id"],
            name=op.f("fk_taxonomy_nodes_taxonomy_id_taxonomies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_nodes")),
    )
    with op.batch_alter_table("taxonomy_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_taxonomy_nodes_taxonomy_id"),
            ["taxonomy_id"],
            unique=False,
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("reason", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_audit_events_version_id_system_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_entity_id"),
            ["entity_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "equipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("taxonomy_node_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("equipment_class", sa.String(length=100), nullable=True),
        sa.Column("equipment_type", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("criticality", sa.String(length=32), nullable=False),
        sa.Column("operating_mode", sa.String(length=32), nullable=False),
        sa.Column("standby_mode", sa.String(length=32), nullable=False),
        sa.Column("is_repairable", sa.Boolean(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["equipment.id"],
            name=op.f("fk_equipment_parent_id_equipment"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_node_id"],
            ["taxonomy_nodes.id"],
            name=op.f("fk_equipment_taxonomy_node_id_taxonomy_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_equipment_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
    )
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_equipment_lineage_id"), ["lineage_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_version_id"), ["version_id"], unique=False
        )

    op.create_table(
        "production_functions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("rate_value", sa.Float(), nullable=False),
        sa.Column("mass_unit", sa.String(length=32), nullable=False),
        sa.Column("time_unit", sa.String(length=32), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_production_functions_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_functions")),
    )
    with op.batch_alter_table("production_functions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_production_functions_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_production_functions_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "reliability_structures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("structure_type", sa.String(length=32), nullable=False),
        sa.Column("k", sa.Integer(), nullable=True),
        sa.Column("parent_structure_id", sa.Uuid(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_structure_id"],
            ["reliability_structures.id"],
            name=op.f(
                "fk_reliability_structures_parent_structure_id_reliability_structures"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_reliability_structures_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reliability_structures")),
    )
    with op.batch_alter_table(
        "reliability_structures", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reliability_structures_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reliability_structures_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("cost_per_hour", sa.Float(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_resources_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
    )
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resources_lineage_id"), ["lineage_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resources_version_id"), ["version_id"], unique=False
        )

    op.create_table(
        "spare_parts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("lead_time_value", sa.Float(), nullable=True),
        sa.Column("lead_time_unit", sa.String(length=32), nullable=True),
        sa.Column("unit_cost", sa.Float(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_spare_parts_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spare_parts")),
    )
    with op.batch_alter_table("spare_parts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_spare_parts_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spare_parts_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "equipment_components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_equipment_components_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_equipment_components_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_components")),
    )
    with op.batch_alter_table("equipment_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_equipment_components_equipment_id"),
            ["equipment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_components_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_components_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "equipment_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("connection_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["equipment.id"],
            name=op.f("fk_equipment_connections_source_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["equipment.id"],
            name=op.f("fk_equipment_connections_target_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_equipment_connections_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_connections")),
    )
    with op.batch_alter_table(
        "equipment_connections", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_equipment_connections_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_connections_source_id"),
            ["source_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_connections_target_id"),
            ["target_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_connections_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "reliability_structure_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("structure_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=True),
        sa.Column("child_structure_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_structure_id"],
            ["reliability_structures.id"],
            name=op.f(
                "fk_reliability_structure_members_child_structure_id_reliability_structures"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f(
                "fk_reliability_structure_members_equipment_id_equipment"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["reliability_structures.id"],
            name=op.f(
                "fk_reliability_structure_members_structure_id_reliability_structures"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f(
                "fk_reliability_structure_members_version_id_system_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_reliability_structure_members")
        ),
    )
    with op.batch_alter_table(
        "reliability_structure_members", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reliability_structure_members_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reliability_structure_members_structure_id"),
            ["structure_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_reliability_structure_members_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "failure_modes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_detectable", sa.Boolean(), nullable=False),
        sa.Column("pf_interval_value", sa.Float(), nullable=True),
        sa.Column("pf_interval_unit", sa.String(length=32), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["equipment_components.id"],
            name=op.f("fk_failure_modes_component_id_equipment_components"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_failure_modes_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_failure_modes_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failure_modes")),
    )
    with op.batch_alter_table("failure_modes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_failure_modes_equipment_id"),
            ["equipment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_failure_modes_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_failure_modes_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "diagnostic_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("failure_mode_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=200), nullable=True),
        sa.Column("interval_value", sa.Float(), nullable=False),
        sa.Column("interval_unit", sa.String(length=32), nullable=False),
        sa.Column("detection_probability", sa.Float(), nullable=False),
        sa.Column("false_positive_probability", sa.Float(), nullable=False),
        sa.Column("duration_value", sa.Float(), nullable=True),
        sa.Column("duration_unit", sa.String(length=32), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_diagnostic_tasks_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["failure_modes.id"],
            name=op.f("fk_diagnostic_tasks_failure_mode_id_failure_modes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_diagnostic_tasks_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_tasks")),
    )
    with op.batch_alter_table("diagnostic_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_diagnostic_tasks_equipment_id"),
            ["equipment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_diagnostic_tasks_failure_mode_id"),
            ["failure_mode_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_diagnostic_tasks_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_diagnostic_tasks_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "failure_distributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("failure_mode_id", sa.Uuid(), nullable=False),
        sa.Column("distribution", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["failure_modes.id"],
            name=op.f(
                "fk_failure_distributions_failure_mode_id_failure_modes"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_failure_distributions_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failure_distributions")),
    )
    with op.batch_alter_table(
        "failure_distributions", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_failure_distributions_failure_mode_id"),
            ["failure_mode_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_failure_distributions_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_failure_distributions_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "maintenance_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("failure_mode_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("interval_value", sa.Float(), nullable=True),
        sa.Column("interval_unit", sa.String(length=32), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_maintenance_tasks_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["failure_modes.id"],
            name=op.f("fk_maintenance_tasks_failure_mode_id_failure_modes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_maintenance_tasks_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_tasks")),
    )
    with op.batch_alter_table("maintenance_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_maintenance_tasks_equipment_id"),
            ["equipment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_tasks_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_tasks_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "production_impacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("failure_mode_id", sa.Uuid(), nullable=True),
        sa.Column("loss_fraction", sa.Float(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_production_impacts_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["failure_modes.id"],
            name=op.f("fk_production_impacts_failure_mode_id_failure_modes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_production_impacts_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_impacts")),
    )
    with op.batch_alter_table("production_impacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_production_impacts_equipment_id"),
            ["equipment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_production_impacts_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_production_impacts_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "maintenance_distributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_task_id", sa.Uuid(), nullable=False),
        sa.Column("distribution", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["maintenance_task_id"],
            ["maintenance_tasks.id"],
            name=op.f(
                "fk_maintenance_distributions_maintenance_task_id_maintenance_tasks"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f(
                "fk_maintenance_distributions_version_id_system_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_maintenance_distributions")
        ),
    )
    with op.batch_alter_table(
        "maintenance_distributions", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_maintenance_distributions_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_distributions_maintenance_task_id"),
            ["maintenance_task_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_distributions_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "maintenance_effects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_task_id", sa.Uuid(), nullable=False),
        sa.Column("effect_type", sa.String(length=64), nullable=False),
        sa.Column("failure_mode_id", sa.Uuid(), nullable=True),
        sa.Column("parameter", sa.Float(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["failure_mode_id"],
            ["failure_modes.id"],
            name=op.f("fk_maintenance_effects_failure_mode_id_failure_modes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_task_id"],
            ["maintenance_tasks.id"],
            name=op.f(
                "fk_maintenance_effects_maintenance_task_id_maintenance_tasks"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_maintenance_effects_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_effects")),
    )
    with op.batch_alter_table("maintenance_effects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_maintenance_effects_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_effects_maintenance_task_id"),
            ["maintenance_task_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_maintenance_effects_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "resource_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_task_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["maintenance_task_id"],
            ["maintenance_tasks.id"],
            name=op.f(
                "fk_resource_requirements_maintenance_task_id_maintenance_tasks"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_resource_requirements_resource_id_resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_resource_requirements_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_requirements")),
    )
    with op.batch_alter_table(
        "resource_requirements", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_requirements_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resource_requirements_maintenance_task_id"),
            ["maintenance_task_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resource_requirements_resource_id"),
            ["resource_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resource_requirements_version_id"),
            ["version_id"],
            unique=False,
        )

    op.create_table(
        "spare_part_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("maintenance_task_id", sa.Uuid(), nullable=False),
        sa.Column("spare_part_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("lineage_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["maintenance_task_id"],
            ["maintenance_tasks.id"],
            name=op.f(
                "fk_spare_part_requirements_maintenance_task_id_maintenance_tasks"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spare_part_id"],
            ["spare_parts.id"],
            name=op.f("fk_spare_part_requirements_spare_part_id_spare_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["system_versions.id"],
            name=op.f("fk_spare_part_requirements_version_id_system_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spare_part_requirements")),
    )
    with op.batch_alter_table(
        "spare_part_requirements", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_spare_part_requirements_lineage_id"),
            ["lineage_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spare_part_requirements_maintenance_task_id"),
            ["maintenance_task_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spare_part_requirements_spare_part_id"),
            ["spare_part_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spare_part_requirements_version_id"),
            ["version_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "spare_part_requirements", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_spare_part_requirements_version_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_spare_part_requirements_spare_part_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_spare_part_requirements_maintenance_task_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_spare_part_requirements_lineage_id")
        )

    op.drop_table("spare_part_requirements")
    with op.batch_alter_table(
        "resource_requirements", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_requirements_version_id"))
        batch_op.drop_index(batch_op.f("ix_resource_requirements_resource_id"))
        batch_op.drop_index(
            batch_op.f("ix_resource_requirements_maintenance_task_id")
        )
        batch_op.drop_index(batch_op.f("ix_resource_requirements_lineage_id"))

    op.drop_table("resource_requirements")
    with op.batch_alter_table("maintenance_effects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_maintenance_effects_version_id"))
        batch_op.drop_index(
            batch_op.f("ix_maintenance_effects_maintenance_task_id")
        )
        batch_op.drop_index(batch_op.f("ix_maintenance_effects_lineage_id"))

    op.drop_table("maintenance_effects")
    with op.batch_alter_table(
        "maintenance_distributions", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_maintenance_distributions_version_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_maintenance_distributions_maintenance_task_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_maintenance_distributions_lineage_id")
        )

    op.drop_table("maintenance_distributions")
    with op.batch_alter_table("production_impacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_production_impacts_version_id"))
        batch_op.drop_index(batch_op.f("ix_production_impacts_lineage_id"))
        batch_op.drop_index(batch_op.f("ix_production_impacts_equipment_id"))

    op.drop_table("production_impacts")
    with op.batch_alter_table("maintenance_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_maintenance_tasks_version_id"))
        batch_op.drop_index(batch_op.f("ix_maintenance_tasks_lineage_id"))
        batch_op.drop_index(batch_op.f("ix_maintenance_tasks_equipment_id"))

    op.drop_table("maintenance_tasks")
    with op.batch_alter_table(
        "failure_distributions", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failure_distributions_version_id"))
        batch_op.drop_index(batch_op.f("ix_failure_distributions_lineage_id"))
        batch_op.drop_index(
            batch_op.f("ix_failure_distributions_failure_mode_id")
        )

    op.drop_table("failure_distributions")
    with op.batch_alter_table("diagnostic_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diagnostic_tasks_version_id"))
        batch_op.drop_index(batch_op.f("ix_diagnostic_tasks_lineage_id"))
        batch_op.drop_index(batch_op.f("ix_diagnostic_tasks_failure_mode_id"))
        batch_op.drop_index(batch_op.f("ix_diagnostic_tasks_equipment_id"))

    op.drop_table("diagnostic_tasks")
    with op.batch_alter_table("failure_modes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failure_modes_version_id"))
        batch_op.drop_index(batch_op.f("ix_failure_modes_lineage_id"))
        batch_op.drop_index(batch_op.f("ix_failure_modes_equipment_id"))

    op.drop_table("failure_modes")
    with op.batch_alter_table(
        "reliability_structure_members", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_reliability_structure_members_version_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_reliability_structure_members_structure_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_reliability_structure_members_lineage_id")
        )

    op.drop_table("reliability_structure_members")
    with op.batch_alter_table(
        "equipment_connections", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equipment_connections_version_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_connections_target_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_connections_source_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_connections_lineage_id"))

    op.drop_table("equipment_connections")
    with op.batch_alter_table("equipment_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equipment_components_version_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_components_lineage_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_components_equipment_id"))

    op.drop_table("equipment_components")
    with op.batch_alter_table("spare_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spare_parts_version_id"))
        batch_op.drop_index(batch_op.f("ix_spare_parts_lineage_id"))

    op.drop_table("spare_parts")
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resources_version_id"))
        batch_op.drop_index(batch_op.f("ix_resources_lineage_id"))

    op.drop_table("resources")
    with op.batch_alter_table(
        "reliability_structures", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reliability_structures_version_id"))
        batch_op.drop_index(batch_op.f("ix_reliability_structures_lineage_id"))

    op.drop_table("reliability_structures")
    with op.batch_alter_table("production_functions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_production_functions_version_id"))
        batch_op.drop_index(batch_op.f("ix_production_functions_lineage_id"))

    op.drop_table("production_functions")
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equipment_version_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_lineage_id"))

    op.drop_table("equipment")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_version_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("taxonomy_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_taxonomy_nodes_taxonomy_id"))

    op.drop_table("taxonomy_nodes")
    with op.batch_alter_table("system_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_versions_system_id"))
        batch_op.drop_index(batch_op.f("ix_system_versions_lineage_id"))

    op.drop_table("system_versions")
    op.drop_table("taxonomies")
    op.drop_table("systems")
    op.drop_table("reference_sources")
    # ### end Alembic commands ###
